template_project/template_app/urls.py
from django.urls import path
from template_app import views

app_name = 'app'
urlpatterns = [
  path('relative/',views.relative,name='relative'),
  path('other/',views.other,name='other'),
]

template_project/template_project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

template_project/template_app/models.py
from django.db import models

# Create your models here.

template_project/template_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
  context_dict = {'text':'hello world','number':100}
  return render(request, 'template_app/index.html',context_dict)

def other(request):
  return render(request, 'template_app/other.html')

def relative(request):
  return render(request, 'template_app/relative_url_templates.html')

template_project/templates/template_app/index.html
<!DOCTYPE html>
{% extends "template_app/base.html"%}
  {% block body_block %}
  <h1>Welcome to HOME</h1>
  <h2>Template inheritance example</h2>
  {{ text|cut:'world' }}
  {{ number|add:"99" }}
  {% endblock %}

template_project/templates/template_app/other.html
<!DOCTYPE html>
{% extends "template_app/base.html"%}
  {% block body_block %}
  <h1>Welcome to other</h1>
  <h2>Template inheritance example</h2>
  {% endblock %}

template_project/templates/template_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <h1>Welcome to relative</h1>
  <a href="{% url 'app:other' %}">Other page</a>
  <a href="{% url 'admin:index' %}">Admin Page</a>
  <a href="{% url 'index' %}">Home</a>
</body>
</html>